version: "3"

services:
  postgres:
    build: .
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "PGPASSWORD=postgres"
    volumes:
      - "./sqlfiles:/var/run/postgresql"
